// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAssOs-ZvsxbslPkjUWhTWN_G3ju7egjIw',
    appId: '1:1033374722697:web:e093142783cd0040917458',
    messagingSenderId: '1033374722697',
    projectId: 'chatapp-backend-8d7a7',
    authDomain: 'chatapp-backend-8d7a7.firebaseapp.com',
    storageBucket: 'chatapp-backend-8d7a7.firebasestorage.app',
    measurementId: 'G-9QJ439PQ80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqEE00j3kE0uSQxz5Qwuu5bV_GDJZ5Ado',
    appId: '1:1033374722697:android:253a462d68fbf82a917458',
    messagingSenderId: '1033374722697',
    projectId: 'chatapp-backend-8d7a7',
    storageBucket: 'chatapp-backend-8d7a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDKfwFKya1LmVxN4o9hSAZfeDczU-YrAc',
    appId: '1:1033374722697:ios:b9ac7c4213ee1067917458',
    messagingSenderId: '1033374722697',
    projectId: 'chatapp-backend-8d7a7',
    storageBucket: 'chatapp-backend-8d7a7.firebasestorage.app',
    iosBundleId: 'com.example.whatsappFlutterUiNew',
  );
}
